# Name of your application. Used to uniquely configure containers.
service: exhiby

# Name of the container image (use your-user/app-name on external registries).
image: stereosupersonic/exhiby

# Deploy to these servers.
servers:
  web:
    - 37.120.188.157
  # job:
  #   hosts:
  #     - 192.168.0.1
  #   cmd: bin/jobs

# Enable SSL auto certification via Let's Encrypt and allow for multiple apps on a single web server.
# If used with Cloudflare, set encryption mode in SSL/TLS setting to "Full" to enable CF-to-app encryption.
#
# Using an SSL proxy like this requires turning on config.assume_ssl and config.force_ssl in production.rb!
#
# Don't use this when deploying to multiple web servers (then you have to terminate SSL at your load balancer).
#
proxy:
  ssl: true
  host: museum-wartenberg.de

# Where you keep your container images.
registry:
  # Alternatives: hub.docker.com / registry.digitalocean.com / ghcr.io / ...
  #server: localhost:5555
  username: stereosupersonic
  # Always use an access token rather than real password when possible.
  password:
    - KAMAL_REGISTRY_PASSWORD


# Inject ENV variables into containers (secrets come from .kamal/secrets).
env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    DATABASE_HOST: exhiby-postgres
    # Run the Solid Queue Supervisor inside the web server's Puma process to do jobs.
    # When you start using multiple servers, you should split out job processing to a dedicated machine.
    SOLID_QUEUE_IN_PUMA: true

    # Set number of processes dedicated to Solid Queue (default: 1)
    # JOB_CONCURRENCY: 3

    # Set number of cores available to the application on each server (default: 1).
    # WEB_CONCURRENCY: 2

    # Match this to any external database server to configure Active Record correctly
    # Use exhiby-db for a db accessory server on same machine via local kamal docker network.
    # DB_HOST: 192.168.0.2

    # Log everything from Rails
    # RAILS_LOG_LEVEL: debug

# Aliases are triggered with "bin/kamal <alias>". You can overwrite arguments on invocation:
# "bin/kamal logs -r job" will tail logs from the first server in the job section.
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

# Use a persistent storage volume for sqlite database files and local Active Storage files.
# Recommended to change this to a mounted volume path that is backed up off server.
volumes:
  - "exhiby_storage:/rails/storage"

# Bridge fingerprinted assets, like JS and CSS, between versions to avoid
# hitting 404 on in-flight requests. Combines all files from new and old
# version inside the asset_path.
asset_path: /rails/public/assets

# Configure the image builder.
builder:
  arch: amd64

  # # Build image via remote server (useful for faster amd64 builds on arm64 computers)
  # remote: ssh://docker@docker-builder-server
  #
  # # Pass arguments and secrets to the Docker build process
  # args:
  #   RUBY_VERSION: 3.3.9
  # secrets:
  #   - GITHUB_TOKEN
  #   - RAILS_MASTER_KEY

# Use a different ssh user than root
# https://kamal-deploy.org/docs/configuration/ssh/
ssh:
  user: stereosonic
  keys:
    - SSH_KEY

accessories:
  postgres:
    image: postgres:18
    port: 127.0.0.1:5432:5432
    host: 37.120.188.157
    env:
      clear:
        POSTGRES_USER: postgres
        POSTGRES_DB: exhiby_production
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data

  # postgres_backup:
  #   image: kartoza/pg-backup:18-3.5
  #   host: 37.120.188.157
  #   env:
  #     clear:
  #       POSTGRES_USER: postgres
  #       POSTGRES_HOST: exhiby-postgres
  #       DBLIST: exhiby_production # Only back up the primary DB
  #       POSTGRES_PORT: 5432
  #       REMOVE_BEFORE: "30"
  #       ARCHIVE_FILENAME: $(date +%Y-%m-%d_%H:%M:%S) # 2025-10-04_10:43:01.exhiby_production.dmp
  #       CRON_SCHEDULE: "0 2 * * *"  # Daily at 2 AM
  #     secret:
  #       - POSTGRES_PASS
  #   directories:
  #     - /home/stereosonic/backups:/backups
