name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  docker:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start containers
        run: |
          docker compose -f docker-compose.test.yml up -d --build
          docker compose -f docker-compose.test.yml ps
          echo "Waiting for services to be ready..."
          sleep 5
          docker compose -f docker-compose.test.yml logs

      - name: Prepare database
        run: |
          docker compose -f docker-compose.test.yml exec -T app bin/rails db:create --trace
          docker compose -f docker-compose.test.yml exec -T app bin/rails db:schema:load --trace

      - name: Run RuboCop
        run: docker compose -f docker-compose.test.yml exec -T app bundle exec rubocop -f github

      - name: Run Brakeman security scan
        run: docker compose -f docker-compose.test.yml exec -T app bin/brakeman --no-pager

      - name: Run Bundler Audit
        run: docker compose -f docker-compose.test.yml exec -T app bundle exec bundler-audit check --update

      - name: Run tests
        run: docker compose -f docker-compose.test.yml exec -e CI=true -T app bundle exec rspec

      - name: Stop containers
        if: always()
        run: docker compose -f docker-compose.test.yml down
